port: 7893
socks-port: 7894
allow-lan: false
mode: Global
proxies:
# socks5
- name: "HKP"
  type: socks5
  server: 192.168.124.17
  port: 7891
  # username: username
  # password: password
  tls: false
  skip-cert-verify: true
  udp: true
- name: "HKM"
  type: socks5
  server: 192.168.124.7
  port: 7892
  # username: username
  # password: password
  tls: false
  skip-cert-verify: true
  udp: true
proxy-groups:
- name: Proxy
  type: select
  proxies:
    - socks
- name: 💩 ‍广告
  type: select
  proxies:
    - REJECT
  
rules:
- DOMAIN-SUFFIX,acl4.ssr,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
